swagger: "2.0"
info:
  title: Renatal Property API
  description: |
    API to browse rental properties. Supports filtering by price,star rating, review score, number of reviews, published status,property type, feed, bedroom count, and amenities.
  version: 1.0.0
  contact:
    email: mdshohagshowdagor001@gmail.com
basePath: /v1
paths:
  /properties/:
    get:
      tags:
      - properties
      description: |-
        get all properties with optional filters
        <br>
      operationId: PropertyController.GetAll
      parameters:
      - in: query
        name: min_price
        description: Minimum USD price
        type: number
        format: double
      - in: query
        name: max_price
        description: Maximum USD price
        type: number
        format: double
      - in: query
        name: min_star_rating
        description: Minimum star rating
        type: integer
        format: int64
      - in: query
        name: min_review_score
        description: Minimum review score
        type: number
        format: double
      - in: query
        name: min_reviews
        description: Minimum number of reviews
        type: integer
        format: int64
      - in: query
        name: published
        description: Published status
        type: boolean
      - in: query
        name: property_type
        description: Property type (Hotel, House, Apartment, Villa, Resort, Hostel)
        type: string
      - in: query
        name: feed
        description: Feed id (11, 12, 22, 24)
        type: integer
        format: int64
      - in: query
        name: min_bedroom
        description: Minimum number of bedrooms
        type: integer
        format: int64
      - in: query
        name: limit
        description: Maximum number of results
        type: integer
        format: int64
      - in: query
        name: amenities
        description: Comma separated amenities
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.SuccessResponse'
        "400":
          description: invalid query parameter
  /properties/{id}:
    get:
      tags:
      - properties
      description: |-
        get property by id
        <br>
      operationId: PropertyController.GetOne
      parameters:
      - in: path
        name: id
        description: The property id
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: property not found
definitions:
  models.Counts:
    title: Counts
    type: object
    properties:
      Bathroom:
        type: integer
        format: int64
      Bedroom:
        type: integer
        format: int64
      Occupancy:
        type: integer
        format: int64
      Reviews:
        type: integer
        format: int64
  models.GeoInfo:
    title: GeoInfo
    type: object
    properties:
      Breadcrumbs:
        type: array
        items:
          $ref: '#/definitions/models.ResponseCategoryItem'
      City:
        type: string
      Country:
        type: string
      CountryCode:
        type: string
      Lat:
        type: number
        format: double
      LocationID:
        type: string
      Lon:
        type: number
        format: double
      Name:
        type: string
      State:
        type: string
      StateAbbr:
        type: string
  models.Image:
    title: Image
    type: object
    properties:
      Count:
        type: integer
        format: int64
      Images:
        type: array
        items:
          type: string
  models.Property:
    title: Property
    type: object
    properties:
      Amenities:
        type: array
        items:
          type: string
      Counts:
        $ref: '#/definitions/models.Counts'
      Image:
        $ref: '#/definitions/models.Image'
      Name:
        type: string
      Price:
        type: number
        format: double
      PropertyType:
        type: string
      ReviewScore:
        type: number
        format: double
      Slug:
        type: string
      StarRating:
        type: integer
        format: int64
  models.Response:
    title: Response
    type: object
    properties:
      Feed:
        type: integer
        format: int64
      GeoInfo:
        $ref: '#/definitions/models.GeoInfo'
      ID:
        type: string
      Property:
        $ref: '#/definitions/models.Property'
      Published:
        type: boolean
  models.ResponseCategoryItem:
    title: ResponseCategoryItem
    type: object
    properties:
      Display:
        type: array
        items:
          type: string
      LocationID:
        type: string
      Name:
        type: string
      Slug:
        type: string
      Type:
        type: string
  models.SuccessResponse:
    title: SuccessResponse
    type: object
    properties:
      Result:
        $ref: '#/definitions/models.SuccessResult'
  models.SuccessResult:
    title: SuccessResult
    type: object
    properties:
      Count:
        type: integer
        format: int64
      Items:
        type: array
        items:
          $ref: '#/definitions/models.Response'
